{% set name = "pyspline" %}

{% set version = environ.get('GIT_DESCRIBE_TAG', '') %}
{% if version.startswith('v') %}
{% set version = version[1:] %}
{% endif %}

{% set build = 0 %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/mdolab/pyspline.git

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - numpy   1.18   # [py==38]
    - numpy   1.19   # [py==39]
    - numpy   1.22   # [py==310]
    - numpy   1.23   # [py==311]
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - setuptools

  host:
    - python {{ python }}
    - numpy   1.18   # [py==38]
    - numpy   1.19   # [py==39]
    - numpy   1.22   # [py==310]
    - numpy   1.23   # [py==311]
    - make
    - setuptools

  run:
    - python
    - numpy >=1.18.5,<2.0.a0   # [py==38]
    - numpy >=1.19.5,<2.0.a0   # [py==39]
    - numpy >=1.22.0,<2.0.a0   # [py==310]
    - numpy >=1.23.0,<2.0.a0   # [py==311]
    - scipy

test:

  imports:
    - pyspline

about:
  home: https://github.com/mdolab/pyspline
  license: Apache
  license_family: APACHE
  summary: "pySpline is a package containing code for wiking with b-spline curve, surface, and volume objects. The Python interface to all functionality is found in the pySpline.py module."
  doc_url: https://mdolab-pyspline.readthedocs-hosted.com/en/latest/
